# Generated by Django 3.0.2 on 2020-02-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0002_auto_20200215_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarydata',
            name='img',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
