# Generated by Django 3.0.2 on 2020-02-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0004_auto_20200215_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarydata',
            name='img1',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='diarydata',
            name='img2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='diarydata',
            name='img3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
